var JSONBingo = {
    "squares": [
        { "square": "Someone is kicked out" },
        { "square": "Sum up the goddamn forces!" },
        { "square": "Erases horribly" },
        { "square": "Speech about conclusion, rule, and evidence" },
        { "square": "Acts super depressed" },
        { "square": "Calls sam his son" },
        { "square": "Imaginary girlfriend from canada" },
        { "square": "Openly admires Mr. Reid" },
        { "square": "Before school, after school, or during tutorial" },
        { "square": "He shaves" },
        { "square": "Nobody gets a stamp (or only ryan)" },
        { "square": "Changes someones seat" },
        { "square": "Can't remember a formula" },
        { "square": "The AP Scores don't matter" },
        { "square": "Says physics is the best subject" },
        { "square": "Everyone gets a stamp" },
        { "square": "Talks about Mr. Old" },
        { "square": "Complains about his other classes" },
        { "square": "When I was a kid I knew this" },
        { "square": "Manipulator, Manipulated Speech" },
        { "square": "Talks about New York" },
        { "square": "Mentions ryans multivariable calculus" },
        { "square": "Mentions Mr. Giddens without being prompted" },
        { "square": "Talks about his golf game" },
        { "square": "Threatens to fail everyone" },
        { "square": "Mentions how he used to have hair" },
        { "square": "Leans on the file cabinet" },
        { "square": "Slams on the board with a marker" },
        { "square": "Leaves the class when someone is talking" },
        { "square": "More than 30 seconds of complete silence" },
        { "square": "Talks about being a lawyer or engineer" },
        { "square": "Talks about tahoe" },
        { "square": "Picks up the wrong period cards" },
        { "square": "Picks another card" },
        { "square": "My turn!" },
        { "square": "Make me earn my money" },
    ]
};